"""empty message

Revision ID: 9b80ef012d9a
Revises: 093c9401cbde
Create Date: 2026-10-09 16:25:17.124949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b80ef012d9a'
down_revision: Union[str, Sequence[str], None] = '093c9401cbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###\

    op.add_column(
        'users',
        column= sa.Column('role', sa.String())
    )

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('users', 'role')
    pass
    # ### end Alembic commands ###
